GET http://localhost:8080/history/patient/97031509099
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInppcCI6IkdaSVAifQ.H4sIAAAAAAAAAKtWyirJVLJSMjNW0lEqLk0CMjPyS4tTgbzM4mIgLzknMy8zGcRNLFGyMjQ1MTcxMDS1MNVRSq0ogApYmFuCBIryc1KBOlz8nUP8g5RqAUQkzAZbAAAA.Efp0Euwg6fFsWPhyouEZonxemW35eUSJqMwLRNuIpos

###

GET http://localhost:8080/opinion/doctor/Gregory-House
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInppcCI6IkdaSVAifQ.H4sIAAAAAAAAAKtWyirJVLJSMjNV0lEqLk0CMpPyc_ILMksSc4AimcXFQJHknMy8zGQQN7FEycrQ1MTcxNTYxMxYRym1ogAiYGpsaQESKMrPSQXqCHAM8XT1C1GqBQDwbEVpYAAAAA.L7Wihy3lz7TpdKAAiROnJtaSrgX1D9os3AQhj2OvW_o

###

POST http://localhost:8080/opinion/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInppcCI6IkdaSVAifQ.H4sIAAAAAAAAAKtWyirJVLJSMjNV0lEqLk0CMpPyc_ILMksSc4AimcXFQJHknMy8zGQQN7FEycrQ1MTcxNTYxMxYRym1ogAiYGpsaQESKMrPSQXqCHAM8XT1C1GqBQDwbEVpYAAAAA.L7Wihy3lz7TpdKAAiROnJtaSrgX1D9os3AQhj2OvW_o

{
  "doctorId": 67,
  "opinion": "Zajebisty lekarz, polecam. Janusz z Łomży",
  "rate":"REALLY_GOOD"
}

###

GET http://localhost:8080/availability/doctor/specialization/CARDIOLOGIST

###

GET http://localhost:8080/availability/doctor/Chris-Taub

###

POST http://localhost:8080/availability/reservation
Content-Type: application/json

{
  "patientId": 1,
  "doctorId": 5,
  "visitStartStr": "2018-12-16T16:00:00",
  "cost": 12345
}

###

GET http://localhost:8080/patient/pesel/95031709099


###

GET http://localhost:8080/patient/name/Konrad-Bolczyk

###

POST http://localhost:8080/patient/register
Content-Type: application/json

{
  "firstName": "Pikej",
  "surname": "Pikejowicz",
  "secondName": null,
  "gender": "MALE",
  "birthDateStr": "1997-03-15",
  "peselStr": "97031509099",
  "street": "pikejowa 666",
  "zipCodeStr": "69-666",
  "city": "Warszawa",
  "provinceStr": "mazowieckie",
  "phoneNumberStr": "987654321"
}

###

POST http://localhost:8080/user/register
Content-Type: application/json

{
  "username": "pikejemJestem",
  "plainPassword": "heheszki",
  "email": "pikej.pikejowicz@gmail.com",
  "userType": "PATIENT"
}

###

POST http://localhost:8080/user/sign-in
Content-Type: application/json

{
  "username": "pikejemJestem",
  "password": "heheszki"
}

###


POST http://localhost:8080/history/create-record
Content-Type: application/json

{
  "patientId": 41,
  "diseaseName": "Pikejoza",
  "diagnosis": "Pacjet z przewlekłym pierdolcem pospolitym.",
  "diagnosisDateStr": "2018-10-10",
  "medicineName": "Xyzal",
  "medicineDiseaseDosage": "2 razy dziennie co 12 godzin."
}

###


GET http://localhost:8080/medicine/Xyzal
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInppcCI6IkdaSVAifQ.H4sIAAAAAAAAAKtWyirJVLJSMjNW0lEqLk0CMjPyS4tTgbzM4mIgLzknMy8zGcRNLFGyMjQ1MTc2t7Q0NNFRSq0ogAiYmJkZgwSK8nNSgTpc_J1D_IOUagE15InTWwAAAA.mFOncqqwZRItMcM4Cq-MqtD3-2lvw-m8tRP8zRWSHi8

###

POST http://localhost:8080/medicine/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInppcCI6IkdaSVAifQ.H4sIAAAAAAAAAKtWyirJVLJSMjNW0lEqLk0CMjPyS4tTgbzM4mIgLzknMy8zGcRNLFGyMjQ1MTc2t7Q0NNFRSq0ogAiYmJkZgwSK8nNSgTpc_J1D_IOUagE15InTWwAAAA.mFOncqqwZRItMcM4Cq-MqtD3-2lvw-m8tRP8zRWSHi8
Content-Type: application/json

{
  "name": "Xyzal",
  "description": "Lek przeciwalergiczny.",
  "sideEffects": "Otępienie, senność."
}

###

GET http://localhost:8080/disease/Pikejoza
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInppcCI6IkdaSVAifQ.H4sIAAAAAAAAAKtWyirJVLJSMjNW0lEqLk0CMjPyS4tTgbzM4mIgLzknMy8zGcRNLFGyMjQ1MTcxMDS1MNVRSq0ogApYmFuCBIryc1KBOlz8nUP8g5RqAUQkzAZbAAAA.Efp0Euwg6fFsWPhyouEZonxemW35eUSJqMwLRNuIpos

###

POST http://localhost:8080/disease/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInppcCI6IkdaSVAifQ.H4sIAAAAAAAAAKtWyirJVLJSMjNW0lEqLk0CMjPyS4tTgbzM4mIgLzknMy8zGcRNLFGyMjQ1MTc2tzQwNdBRSq0ogAiYmJmagASK8nNSgTpc_J1D_IOUagH1q49HWwAAAA.eehMA628tV_PfT058DhZh5rHZ5hrRq3FmP4oEszJ5lE

{
  "name": "Pikejoza",
  "description": "Choroba bezobjawowa atakująca studentów WAT."
}

###

#################################################################

###

POST http://localhost:8080/user/register
Content-Type: application/json

{
  "username": "bolopital",
  "plainPassword": "jebacWat",
  "email": "bolowiecki@gmail.com",
  "userType": "PATIENT"
}

###

POST http://localhost:8080/public/auth/login
Content-Type: application/json

{
  "username": "house",
  "password": "housowicz"
}

###

###

POST http://localhost:8080/public/auth/login
Content-Type: application/json

{
  "username": "bolopital",
  "password": "jebacWat"
}

###

POST http://localhost:8080/patient/register/own
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInppcCI6IkdaSVAifQ.H4sIAAAAAAAAAKtWyirJVLJSMjNV0lEqLk0CMpPyc_ILMksSc4AimcXFQJHknMy8zGQQN7FEycrQ1MTc2MLU1MJARym1ogAiYGJuaAkSKMrPSQXqCHAM8XT1C1GqBQDCAwN5YAAAAA.scqdq8w5SRb6EclXJ5yL_8UzFiZLRIpxabT-YfYEeDA

{
  "firstName": "Bolo",
  "surname": "Bolowicz",
  "secondName": null,
  "gender": "MALE",
  "birthDateStr": "1997-03-15",
  "peselStr": "97031509099",
  "street": "pikejowa 666",
  "zipCodeStr": "69-666",
  "city": "Warszawa",
  "provinceStr": "mazowieckie",
  "phoneNumberStr": "987654321"
}

###

GET http://localhost:8080/doctor/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInppcCI6IkdaSVAifQ.H4sIAAAAAAAAAKtWyirJVLJSMjNV0lEqLk0CMpPyc_ILMksSc4AimcXFQJHknMy8zGQQN7FEycrQ1MTc2MLU3NJCRym1ogAiYGJuZAgSKMrPSQXqCHAM8XT1C1GqBQCD2n85YAAAAA.hKJjXR8PhQ-eNLDmhPLpZjgShwk4Sc5yHJYilhFMklQ

###

GET http://localhost:8080/package/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInppcCI6IkdaSVAifQ.H4sIAAAAAAAAAKtWyirJVLJSMjNV0lEqLk0CMpPyc_ILMksSc4AimcXFQJHknMy8zGQQN7FEycrQ1MTcxMDI3NxURym1ogAqYGFpCBIoys9JBeoIcAzxdPULUaoFAMTzO-lgAAAA.gRBcgs9L9hWKcrrz44WJUjF_rCmcBb3B_f5QXJ259a0

###

POST http://localhost:8080/package/purchase
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInppcCI6IkdaSVAifQ.H4sIAAAAAAAAAKtWyirJVLJSMjNV0lEqLk0CMpPyc_ILMksSc4AimcXFQJHknMy8zGQQN7FEycrQ1MTcxMDI3NxURym1ogAqYGFpCBIoys9JBeoIcAzxdPULUaoFAMTzO-lgAAAA.gRBcgs9L9hWKcrrz44WJUjF_rCmcBb3B_f5QXJ259a0

{
  "benefitPackageId": 1
}

###
GET http://localhost:8080/patient/pesel/97031509099
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInppcCI6IkdaSVAifQ.H4sIAAAAAAAAAKtWyirJVLJSMjNW0lEqLk0CMjPyS4tTgbzM4mIgLzknMy8zGcRNLFGyMjQ1MTc1MTSzsNRRSq0ogAiYGVkYgASK8nNSgTpc_J1D_IOUagGYdLaCWwAAAA.5Wu99Oric6lZGvUfar49dXTeJxNsxpMG2QVx9VJY-H8

###
GET http://localhost:8080/patient/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInppcCI6IkdaSVAifQ.H4sIAAAAAAAAAKtWyirJVLJSMjNW0lEqLk0CMjPyS4tTgbzM4mIgLzknMy8zGcRNLFGyMjQ1MTczNzY1M9FRSq0ogAiYm1paggSK8nNSgTpc_J1D_IOUagEw2qsrWwAAAA.S0K5IzG8VX209XGlZ9dAkhXQFQsOGkQvOGvwZSBIRYM

###